apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "optimus-prime.fullname" . }}-config
  labels:
    app: {{ include "optimus-prime.fullname" . }}
    {{- include "optimus-prime.labels" . | nindent 4 }}
data:
{{ .Values.configMap | toYaml | indent 2 -}}