{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "optimus-prime.serviceAccountName" . }}
  labels:
    app: {{ include "optimus-prime.fullname" . }}
    {{- include "optimus-prime.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
